# Generated by Django 3.0.2 on 2020-01-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dono', '0002_auto_20200113_1111'),
        ('cachorros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachorro',
            name='cor_pelo',
        ),
        migrations.AddField(
            model_name='cachorro',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('LARANJA', 'Laranja'), ('CINZA', 'Cinza'), ('TRICOLOR', 'Tricolor'), ('BEGE', 'Bege')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cachorro',
            name='dono',
        ),
        migrations.AddField(
            model_name='cachorro',
            name='dono',
            field=models.ManyToManyField(to='dono.Dono'),
        ),
        migrations.AlterField(
            model_name='cachorro',
            name='porte',
            field=models.CharField(choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Medio'), ('GRANDE', 'Grande')], max_length=100),
        ),
    ]
